const productos = [
    {
        id:1,
        nombre: "Taza Cerámica",
        precio: 22.90,
        img:"../imagenes/taza.jpg",
        stock:10,
    },
    {
        id:2,
        nombre: "Minifiguras Colección",
        precio: 60.00,
        img:"../imagenes/minifiguras.jpg",
        stock:8,
    },
    {
        id:3,
        nombre: "Vaso de Acero inoxidable",
        precio: 22.90,
        img:"../imagenes/vaso.jpg",
        stock:10,
    },
    {
        id:4,
        nombre: "Mouse pad minions",
        precio: 17.90,
        img:"../imagenes/mouse.webp",
        stock:5,
    },
    {
        id:5,
        nombre: "Funko minions isla",
        precio: 180.00,
        img:"../imagenes/funko1.webp",
        stock:20,
    },
    {
        id:6,
        nombre: "Minions Armable",
        precio: 50.00,
        img:"../imagenes/juguete.jpg",
        stock:10,
    },
    {
        id:7,
        nombre: "Minions Instax",
        precio: 120.90,
        img:"../imagenes/instax.jpg",
        stock:10,
    },
    {
        id:8,
        nombre: "Funko mini minion rey",
        precio: 130.90,
        img:"../imagenes/funko3.jpg",
        stock:10,
    },
    {
        id:9,
        nombre: "Funko mini minion baby",
        precio: 120.90,
        img:"../imagenes/funko2.jpg",
        stock:10,
    },
    {
        id:10,
        nombre: "Llaveros coleccion",
        precio: 120.90,
        img:"../imagenes/llaveros.jpg",
        stock:10,
    },
    {
        id:11,
        nombre: "Funkos minions colección",
        precio: 160.00,
        img:"../imagenes/funkos.webp",
        stock:10,
    },
    {
        id:12,
        nombre: "Funko i love gru",
        precio: 160.90,
        img:"../imagenes/funko5.jpg",
        stock:10,
    },
    {
        id:13,
        nombre: "Powerbank colección minions",
        precio: 80.90,
        img:"../imagenes/powerbank.webp",
        stock:10,
    },
    {
        id:14,
        nombre: "Funko minion patito",
        precio: 70.90,
        img:"../imagenes/funko4.jpg",
        stock:10,
    },
    {
        id:15,
        nombre: "Audifonos minions coleccion",
        precio: 60.00,
        img:"../imagenes/audifonos.jpg",
        stock:10,
    },
    {
        id:16,
        nombre: "Mouse pad minion 2",
        precio: 17.00,
        img:"../imagenes/mouse1.webp",
        stock:10,
    },
];